version: '3'
services:

  db:
    image: yobasystems/alpine-mariadb
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mydb
    - MYSQL_USER=php
    - MYSQL_PASSWORD=php_password
    ports:
    - 3305:3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8081:8080
 
  mail:
    image: cd2team/mailhog
    ports:
    - 8025:8025
    - 1025:1025
  www:
    depends_on:
    - db
    - mail
    image: php:rc-apache-buster
    volumes:
    - "/var/www/html:/var/www/html"
    ports:
    - 9000:8080